master:
  review:
    - stages:
      - name: CR 通过后自动合并
        type: git:automerge
        options:
          mergeType: rebase
          removeSourceBranch: true
          ignoreAssignee: true
        exports:
          reviewedBy: REVIEWED_BY
      - name: notify
        type: wework:message
        options:
          robot: 25dcf80a-ff7c-422c-9b5b-1951cee42f4c
          chatId: wrkSFfCgAAjWlVtrYwk5xNzuRwijAv_Q
          visibleToUser: ${ORANGE_BUILD_USER}
          message: |
            > CR 通过后自动合并 <@${ORANGE_BUILD_USER}>
            > 　
            > ${ORANGE_MERGE_REQUEST_TITLE}
            > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
            >
            > ${REVIEWED_BY}

  merge_request:
    - name: 检查代码质量流水线
      runner:
        network: devnet

      stages:
        # 提交注释检查
        - name: commit lint
          type: epc:commit-lint

        # issue 状态检查，是否正确的扭转状态
        - name: issue lint
          type: git:issueUpdate
          options:
            lint:
              # 检查 issue 当前是否处于，accepted 或 resolved状态
              acceptance:
                - accepted
                - resolved

        # 代码规范检查
        - name: eslint-config-tencent
          script: "tnpm install \ &&
          tnpm run lint"

        # 发送到 CR 专用群
        - name: notify
          type: wework:message
          options:
            robot: 25dcf80a-ff7c-422c-9b5b-1951cee42f4c
            message: |
              > 发送到 CR 专用群
              > 　
              > ${ORANGE_MERGE_REQUEST_TITLE}
              > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
              > 　
              > from ${ORANGE_BUILD_USER}


  push:
    - name: push流水线
      stages:
        # 更新 issue 状态为已解决并关闭，对应 EPC 考核中的 开发完成时间点
        - name: update issue
          type: git:issueUpdate
          options:
            state: close
            acceptance: resolved

      env:
          PRODUCTION: true
      label:
        type:
          - MASTER
          - PRE_RELEASE
        class:
          - MAIN
          - RELIABILITY

$:
  tag_push:
    - name: tag push 流水线
      label:
        type: RELEASE
      git:
        dotGit: true

      stages:
        # 自动生成 CHANGELOG.md
        - name: changelog
          type: git:changeLog
          options:
            filename: CHANGELOG.md
            target: master
          exports:
            latestChangeLog: LATEST_CHANGE_LOG

        # 更新 release 的描述，release 如不存在会自动创建
        - name: upload release
          type: git:release
          options:
            description: ${LATEST_CHANGE_LOG}

        # 更新 issue 状态，增加标签，对应 EPC 考核中的 lead time 结束时间点
        - name: update issue
          type: git:issueUpdate
          options:
            fromText: ${LATEST_CHANGE_LOG}
            label:
              add: 需求已接收
            when:
              label: feature

        # 替换版本号
        # - name: replace version
        #   script: 
        #     - npm version ${ORANGE_BRANCH} --no-git-tag-version
        #     - echo ${ORANGE_TAG_CREATE_FROM}

        # 将自己的工蜂 private token 注入
        - name: get git token
          type: git:set-token
          imports: https://git.woa.com/gcd/social-private-key/blob/master/tdf-devtools/git-token.yml
          options:
            token: ${TGIT_PERSONAL_ACCESS_TOKEN}
            name: sicilyliu
            email: sicilyliu@tencent.com

        # 发布新版本
        - name: commit new version and publish
          imports: https://git.woa.com/gcd/social-private-key/blob/master/tdf-devtools/npm-token.yml
          script: 
            - node auto-publish-by-tag.js

        # 通知 CR 专用群 npm 包发布
        - name: notify npm publish
          type: wework:message
          options:
          robot: 25dcf80a-ff7c-422c-9b5b-1951cee42f4c
          message: |
            > npm 包已发布
            > 　
            > version: ${ORANGE_BRANCH}
            > 　
            > published by ${ORANGE_BUILD_USER}

      failStages:
        - name: echo log
          script:
            - cat oci-log.log
