master:
  review:
    - stages:
      - name: CR 通过后自动合并
        type: git:automerge
        options:
          mergeType: rebase
          removeSourceBranch: true
          ignoreAssignee: true
        exports:
          reviewedBy: REVIEWED_BY
      - name: notify
        type: wework:message
        options:
          robot: 25dcf80a-ff7c-422c-9b5b-1951cee42f4c
          chatId: wrkSFfCgAAjWlVtrYwk5xNzuRwijAv_Q
          visibleToUser: ${ORANGE_BUILD_USER}
          message: |
            > CR 通过后自动合并 <@${ORANGE_BUILD_USER}>
            > 　
            > ${ORANGE_MERGE_REQUEST_TITLE}
            > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
            >
            > ${REVIEWED_BY}
  merge_request:
    - name: MR流水线
      runner:
        network: devnet
      stages:
        # 提交注释检查
        - name: commit lint
          type: epc:commit-lint
        - name: 代码安全审计
          type: security:code-scan
          options:
            sourcePath: src
            ignoreFolder: src/public
        # 代码规范检查
        - name: eslint-config-tencent
          script: "tnpm install && tnpm run lint"
        # 发送到 CR 专用群
        - name: notify
          type: wework:message
          options:
            robot: 25dcf80a-ff7c-422c-9b5b-1951cee42f4c
            message: |
              > 发送到 CR 专用群
              > 　
              > ${ORANGE_MERGE_REQUEST_TITLE}
              > [${ORANGE_EVENT_URL}](${ORANGE_EVENT_URL})
              > 　
              > from ${ORANGE_BUILD_USER}
  push:
    - name: push流水线
      ifModify:
        - src/**
        - package.json
        - package-lock.json
      stages:
        # 更新 issue 状态为已解决并关闭，对应 EPC 考核中的 开发完成时间点
        - name: update issue
          type: git:issueUpdate
          options:
            state: close
            acceptance: resolved
        - name: create version branch
          type: git:create-branch
          options:
            ref: ${ORANGE_BRANCH}
            branchName: version/${ORANGE_BUILD_ID}

$:
  tag_push:
    - name: tag push 流水线
      label:
        type: RELEASE
      git:
        dotGit: true

      stages:
        # 自动生成 CHANGELOG.md
        - name: changelog
          type: git:changeLog
          options:
            filename: CHANGELOG.md
            target: master
          exports:
            latestChangeLog: LATEST_CHANGE_LOG

        # 更新 release 的描述，release 如不存在会自动创建
        - name: upload release
          type: git:release
          options:
            description: ${LATEST_CHANGE_LOG}

        # 更新 issue 状态，增加标签，对应 EPC 考核中的 lead time 结束时间点
        - name: update issue
          type: git:issueUpdate
          options:
            fromText: ${LATEST_CHANGE_LOG}
            label:
              add: 需求已接收
            when:
              label: feature

        # 将自己的工蜂 private token 注入
        - name: get git token
          type: git:set-token
          imports: https://git.woa.com/gcd/social-private-key/blob/master/tdf-devtools/git-token.yml
          options:
            token: ${TGIT_PERSONAL_ACCESS_TOKEN}
            name: sicilyliu
            email: sicilyliu@tencent.com

version/*:
  push:
    - wework: 
        title: Publish debug-server-next
      docker:
        image: node:12
      stages:
        - name: npm i
          script: npm install --registry=https://mirrors.tencent.com/npm/
        - name: set npm orign
          script: npm config set registry https://registry.npmjs.org
        - name: build
          script: npm run build
        - name: patch version
          script: npm version patch
        - name: npm publish
          image: plugins/npm
          envFrom: https://git.woa.com/gcd/social-private-key/blob/master/tdf-devtools/npm-token.yml
          settings: &publish-settings
            token: $NPM_TOKEN
            email: $EMAIL
            fail_on_version_conflict: true
        - name: commit change
          type: git:commit
          options:
            commitMessage: 'version: publish new version'
        - name: create mr
          if: |
            [ "${MR_TARGET_BRANCH}" != "none" ]
          type: git:make-mr
          options:
            target: master
            title: 版本号修改
            reviewers: $ORANGE_BUILD_USER
        - name: notify npm publish
          type: wework:message
          options:
            robot: 25dcf80a-ff7c-422c-9b5b-1951cee42f4c
            message: |
              > npm 包已发布
              > 　
              > published by ${ORANGE_BUILD_USER}
